#!/usr/bin/env bash
# Install the poller (or dashboard) as a systemd service for THIS user and
# THIS checkout.
#
# The shipped unit file hardcodes "pi" and /home/pi, so every install whose
# user isn't pi had to edit it — and the obvious place to edit is the copy in
# the repo, which leaves the working tree permanently dirty and turns the next
# `git pull` into a merge conflict. Generating the unit instead means the
# tracked file is never touched.
#
#   ./systemd/install-service.sh              # the order poller
#   ./systemd/install-service.sh dashboard    # the web dashboard
#   ./systemd/install-service.sh run --print  # show the unit, install nothing

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMAND="run"
PRINT_ONLY=""

for arg in "$@"; do
    case "$arg" in
        run|dashboard) COMMAND="$arg" ;;
        --print) PRINT_ONLY=1 ;;
        *) echo "Usage: $0 [run|dashboard] [--print]" >&2; exit 2 ;;
    esac
done

# Under sudo, $USER is root — which would install a service running as root
# against a venv and config owned by someone else.
RUN_USER="${SUDO_USER:-$(id -un)}"

BINARY="$REPO/.venv/bin/etsy-auto-print"
if [ -z "$PRINT_ONLY" ] && [ ! -x "$BINARY" ]; then
    echo "No etsy-auto-print in $REPO/.venv — create the venv first:" >&2
    echo "  python3 -m venv .venv && .venv/bin/pip install -e ." >&2
    exit 1
fi

if [ "$COMMAND" = "dashboard" ]; then
    NAME="etsy-auto-print-dashboard"
    DESCRIPTION="Etsy auto-print web dashboard"
else
    NAME="etsy-auto-print"
    DESCRIPTION="Etsy auto-print order poller"
fi

UNIT=$(cat <<UNIT_TEXT
# Generated by systemd/install-service.sh — edit that, or this file in
# /etc/systemd/system, but not the template in the repo.
[Unit]
Description=$DESCRIPTION
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$REPO
ExecStart=$BINARY $COMMAND
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
UNIT_TEXT
)

if [ -n "$PRINT_ONLY" ]; then
    printf '%s\n' "$UNIT"
    exit 0
fi

if [ "$RUN_USER" = "root" ]; then
    echo "Refusing to install a service that runs as root." >&2
    echo "Run this as your normal user; it will ask for sudo when it needs it." >&2
    exit 1
fi

TARGET="/etc/systemd/system/$NAME.service"

# A symlink to the repo would make `git checkout` and `git pull` silently
# rewrite the running service. Replace it with a real file and say so.
if [ -L "$TARGET" ]; then
    echo "Note: $TARGET was a symlink into the repo; replacing it with a copy"
    echo "so that git operations can't change what the service runs."
fi

printf '%s\n' "$UNIT" | sudo tee "$TARGET" >/dev/null
sudo chmod 644 "$TARGET"
sudo systemctl daemon-reload
sudo systemctl enable --now "$NAME"

echo
echo "Installed $TARGET"
echo "  user:    $RUN_USER"
echo "  command: $BINARY $COMMAND"
echo
sudo systemctl status "$NAME" --no-pager | head -5
